  
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-secrets"
  labels:
    app: {{ template "charts.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
type: Opaque
data:
  VCAP_SERVICES: {{ default "MISSING" .Values.secrets.VCAP_SERVICES | b64enc | quote }}
  VCAP_APPLICATION: {{ default "MISSING" .Values.secrets.VCAP_APPLICATION | b64enc | quote }}
